# Generated by Django 3.0.2 on 2020-02-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apibricsa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=60)),
            ],
        ),
    ]
